specVersion: 0.2.0
name: karura-scanql
version: 1.0.0
description: ""
repository: ""
schema:
  file: ./schema.graphql
network:
  genesisHash: "0xbaf5aabe40646d11f0ee8abbdc64f4a4b7674925cba08e4a05ff9ebed6e2126b"
  endpoint: wss://karura.api.onfinality.io/public-ws
  chaintypes:
    file: ./types.json
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleCall
          kind: substrate/CallHandler
        - handler: handleEvent
          kind: substrate/EventHandler
